# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: IMI materijali
email: imi.knezevic@gmail.com
description: >
  Sajt koji sadrži lekcije raznih kurseva.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://knezevicmarko.github.io" # the base hostname & protocol for your site

# Build settings
sass:
  sass_dir: _sass
indlude: ['_pages']
highlighter: rouge
markdown: kramdown
excerpt_separator: ""

collections:
  os1:
    title: Operativni sistemi 1
    output: true
    image: fa fa-code
    description:
      Uvod u operativne sisteme. Hardverski i softverski koncepti. Koncepti procesa. Asinhrono konkurentno izvođenje. Konkurentno programiranje. Zastoj i neodređeno odlaganje. Vremensko planiranje procesa. Organizacija realne memorije i upravljanje. Organizacija virtualne memorije. Upravljanje bitruelnom memorijom. Optimizacija performansi diska. Sistemi podataka i datoteka.
  os2:
    title: Operativni sistemi 2
    output: true
    image: fa fa-tasks
    description:
      Upravljanje ulazno/izlaznim uređajima i raspoređivanje diska. Fajl sistemi. Jednoprocesorsko raspoređivanje (scheduling). Višeprocesorsko raspoređivanje i raspođivanje u realnom vremenu. Distribuirani sistemi, klijent/serveri i klasteri. Grid računarstvo. Sigurnost i bezbednost računarskih sistema.
  bp1:
    title: Baze podataka 1
    output: true
    image: fa fa-database
    description:
      Struktura podataka. Klasifikacija, elementi fizičke i logičke strukture, čuvanje podataka. Opšta struktura sistema za upravljanje bazama podataka. Modeli baza podataka. Osnovni tehnološko-tehnički koncepti. Baze podataka i metodologija razvoja IS. ER model. Entitetski i referencijalni integritet. Relacioni model. Struktura relacionog modela. Operacije relacionog modela. Relacioni upitni jezik. Razvoj SQL-a, tipovi podataka i naredbe. Pogledi. Ugrađeni SQL. Preslikavanje konceptualne šeme na relacionu šemu. Programiranje u relacionim bazama podataka. Upravljanje transakcijama. Oporavak BP. Normalne forme-projektovanje relacija normalizacijom. Dizajniranje logičke i fizičke strukture baze podataka i podešavanje. Memorisanje podataka i indeksiranje. Uvod u optimizaciju upita. RDBMS. Struktura datoteka. Prostor za tabele i segmenti. Korisnički objekti BP. Tipovi podataka. Memorijska struktura. Struktura procesa. Upravljanje RDBMS-om.

  vp:
    title: Vizuelno programiranje
    output: true
    image: fa fa-desktop
    description:
        Radna okolina alata za vizuelno programiranje i njeni sa¬stav¬ni delovi. Pojam događaja i biblioteke komponenti. Osnovne komponente. Osnove programskog jezika - kontrolne strukture i tipovi podataka. Komponente sistema za interakciju sa korisnikom, za pristup podacima i bazama podataka, i za izveštaje. Prozori (forme), njihovo kreiranje, pozivanje i uništavanje. Napredne komponente. Elementi multimedije. .Net Studio C#, Java NET Beans. Praktična nastava. Korišćenje integrisanih razvojnih okruženja za razvoj vizuelnih aplikacija. Samostalno kreiranje aplikacija i elemenata aplikacija sa vizuelnim korisničkim interfejsom.
  op:
    title: Osnovi programiranja
    output: true
    image: fa fa-file-code-o
    description:
       Elementi programskog jezika C. Ulazno izlazne naredbe. Naredbe grananja. Naredbe ponavljanja. Funkcije i procedure. Složeni tipovi podataka. Nizovi. Strukture. Datoteke.
